language: python
sudo: required

addons:
  chrome: stable

install: 
  - pip install robotframework
  - pip install robotframework-selenium2library

python:
  - "3.5"
  
before_install:
  - echo $PATH
  - pip install selenium
  - wget https://chromedriver.storage.googleapis.com/2.35/chromedriver_linux64.zip
  - unzip chromedriver_linux64.zip -d test/driver/
  
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3

script: 
  - robot Tests
